"""
This file was generated by Codex to debug my Llama-3.2-1B-Instruct
implementation with reference implementation.
"""

import json
import safetensors
import torch
from einops import rearrange
from transformers import AutoModelForCausalLM, AutoTokenizer

import os
import sys

parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)

import model as student_model

WEIGHTS_PATH = "/Users/yy0125/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct/snapshots/9213176726f574b556790deb65791e0c5aa438b6/model.safetensors"
CONFIG_PATH = "/Users/yy0125/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct/snapshots/9213176726f574b556790deb65791e0c5aa438b6/config.json"
MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"


def max_abs_diff(a: torch.Tensor, b: torch.Tensor) -> float:
    return (a.float() - b.float()).abs().max().item()


def mean_abs_diff(a: torch.Tensor, b: torch.Tensor) -> float:
    return (a.float() - b.float()).abs().mean().item()


def print_diff(name: str, a: torch.Tensor, b: torch.Tensor) -> None:
    print(
        f"{name}: max_abs={max_abs_diff(a, b):.6f}, mean_abs={mean_abs_diff(a, b):.6f}"
    )


def rotate_half(x: torch.Tensor) -> torch.Tensor:
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_reference_rope(
    q: torch.Tensor, k: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor
) -> tuple[torch.Tensor, torch.Tensor]:
    cos = cos.unsqueeze(1)
    sin = sin.unsqueeze(1)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def load_student() -> student_model.LlamaLM:
    with open(CONFIG_PATH, "r") as f:
        config = json.load(f)

    llama = student_model.LlamaLM(
        vocab_size=config["vocab_size"],
        context_length=config["max_position_embeddings"],
        d_model=config["hidden_size"],
        num_layers=config["num_hidden_layers"],
        num_q_heads=config["num_attention_heads"],
        num_kv_heads=config["num_key_value_heads"],
        d_ff=config["intermediate_size"],
        rope_theta=config["rope_theta"],
    )

    translated = {}
    state_dict = llama.state_dict()
    with safetensors.safe_open(WEIGHTS_PATH, framework="pt") as f:

        def set_key(ckpt_name: str, model_name: str) -> None:
            tensor = f.get_tensor(ckpt_name)
            assert tensor.shape == state_dict[model_name].shape
            translated[model_name] = tensor

        set_key("model.embed_tokens.weight", "token_embeddings.weight")
        set_key("model.embed_tokens.weight", "lm_head.weight")

        for layer_idx in range(config["num_hidden_layers"]):
            set_key(
                f"model.layers.{layer_idx}.input_layernorm.weight",
                f"layers.{layer_idx}.ln1.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.self_attn.q_proj.weight",
                f"layers.{layer_idx}.attn.q_proj.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.self_attn.k_proj.weight",
                f"layers.{layer_idx}.attn.k_proj.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.self_attn.v_proj.weight",
                f"layers.{layer_idx}.attn.v_proj.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.self_attn.o_proj.weight",
                f"layers.{layer_idx}.attn.output_proj.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.post_attention_layernorm.weight",
                f"layers.{layer_idx}.ln2.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.mlp.up_proj.weight",
                f"layers.{layer_idx}.ffn.w3.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.mlp.gate_proj.weight",
                f"layers.{layer_idx}.ffn.w1.weight",
            )
            set_key(
                f"model.layers.{layer_idx}.mlp.down_proj.weight",
                f"layers.{layer_idx}.ffn.w2.weight",
            )

        set_key("model.norm.weight", "ln_final.weight")

    llama.load_state_dict(translated, strict=True)
    return llama


def main() -> None:
    device = "mps" if torch.backends.mps.is_available() else "cpu"

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    reference = AutoModelForCausalLM.from_pretrained(MODEL_NAME).to(device).eval()
    student = load_student().to(device).eval()

    encoded = tokenizer("How are you?", return_tensors="pt")["input_ids"].to(device)

    with torch.no_grad():
        ref_embeds = reference.model.embed_tokens(encoded)
        stu_embeds = student.token_embeddings(encoded)
        print_diff("embeds", stu_embeds, ref_embeds)

        ref_layer0 = reference.model.layers[0]
        stu_layer0 = student.layers[0]

        ref_normed = ref_layer0.input_layernorm(ref_embeds)
        stu_normed = stu_layer0.ln1(stu_embeds)
        print_diff("layer0.ln1", stu_normed, ref_normed)

        ref_q = ref_layer0.self_attn.q_proj(ref_normed)
        stu_q = stu_layer0.attn.q_proj(stu_normed)
        print_diff("layer0.q_proj", stu_q, ref_q)

        ref_k = ref_layer0.self_attn.k_proj(ref_normed)
        stu_k = stu_layer0.attn.k_proj(stu_normed)
        print_diff("layer0.k_proj", stu_k, ref_k)

        ref_q_heads = rearrange(ref_q, "b s (h d) -> b h s d", h=32)
        stu_q_heads = rearrange(stu_q, "b s (h d) -> b h s d", h=32)
        ref_k_heads = rearrange(ref_k, "b s (h d) -> b h s d", h=8)
        stu_k_heads = rearrange(stu_k, "b s (h d) -> b h s d", h=8)
        print_diff("q_heads_pre_rope", stu_q_heads, ref_q_heads)
        print_diff("k_heads_pre_rope", stu_k_heads, ref_k_heads)

        position_ids = torch.arange(encoded.shape[-1], device=device).unsqueeze(0)
        cos, sin = reference.model.rotary_emb(ref_embeds, position_ids)
        ref_q_rope, ref_k_rope = apply_reference_rope(
            ref_q_heads, ref_k_heads, cos, sin
        )

        stu_cos, stu_sin = stu_layer0.attn.positional_encoder(stu_q_heads)
        stu_q_rope, stu_k_rope = student_model.apply_rotary_pos_emb(
            stu_q_heads, stu_k_heads, stu_cos, stu_sin
        )

        print_diff("q_post_rope_student_vs_reference", stu_q_rope, ref_q_rope)
        print_diff("k_post_rope_student_vs_reference", stu_k_rope, ref_k_rope)

        # Apply the reference RoPE to the student's pre-RoPE Q/K to isolate whether
        # the gap comes from the frequency schedule or from earlier projections.
        stu_q_with_ref_rope, stu_k_with_ref_rope = apply_reference_rope(
            stu_q_heads.to(ref_q_heads.dtype),
            stu_k_heads.to(ref_k_heads.dtype),
            cos,
            sin,
        )
        print_diff(
            "student_q_with_reference_rope_vs_reference",
            stu_q_with_ref_rope,
            ref_q_rope,
        )
        print_diff(
            "student_k_with_reference_rope_vs_reference",
            stu_k_with_ref_rope,
            ref_k_rope,
        )

        ref_attn = torch.nn.functional.scaled_dot_product_attention(
            ref_q_rope,
            ref_k_rope,
            rearrange(
                ref_layer0.self_attn.v_proj(ref_normed), "b s (h d) -> b h s d", h=8
            ),
            is_causal=True,
            enable_gqa=True,
        )
        stu_attn = torch.nn.functional.scaled_dot_product_attention(
            stu_q_rope,
            stu_k_rope,
            rearrange(stu_layer0.attn.v_proj(stu_normed), "b s (h d) -> b h s d", h=8),
            is_causal=True,
            enable_gqa=True,
        )
        print_diff("attention_output_pre_o_proj", stu_attn, ref_attn)

        ref_hidden = ref_layer0(ref_embeds, position_embeddings=(cos, sin))
        stu_hidden = stu_layer0(stu_embeds)
        print_diff("layer0_output", stu_hidden, ref_hidden)


if __name__ == "__main__":
    main()
